### ISSUE TITLE
Allow usage of `wasm2lua` without static linking to `libc` / Incorrect error message when `mallocName` is undefined

### ISSUE THREAD

**Issue by Vurv78** [SwadicalRag/wasm2lua#30]
So I've been getting this project to work and I can't seem to find how to define ``__MALLOC__`` and ``__FREE__``.. leading to ``undefined is not defined`` (or ``x is not defined`` if using ``--mallocName x`` etc)
I've had to manually replace them with ``function() return 0 end``, ``function() end`` after generating.

In the future I want to be able to automate this, so I wanted to put this here to see how to do so ( The examples didn't give me any clues either :v )

Also seems that someone else had the same issue as seen in the README https://github.com/EntireTwix/wasm2minecraft

This project is amazing btw, thank you for your work on it! (If I have time hopefully I can try and contribute..)
Already got it (mostly) working on windows! (examples may or may not work)

**Comment by SwadicalRag** [comment]
1) `undefined is not defined` is a user experience bug, [this code](https://github.com/SwadicalRag/wasm2lua/blob/4dea912503b03238f8664cd2ec3503641294bf8b/src/index.ts#L538-L541) should be

```diff
-this.writeLn(this.outBuf,`local __MALLOC__ = ${malloc ? malloc.id : `function() error "${this.options.webidl.mallocName} is not defined" end`}`);
+this.writeLn(this.outBuf,`local __MALLOC__ = ${malloc ? malloc.id : `function() error "${this.options.webidl.mallocName || "malloc"} is not defined" end`}`);
```

2) hm, uhh, hmm

When I last used this project, malloc was defined and exported alongside whatever program you were compiling to a `.wasm` file. The default symbol for `malloc` was just simply `malloc`. This is because `libc` was being compiled into the WASM file too.

Here's what the code was trying to reference

![image](https://user-images.githubusercontent.com/10724598/142626910-07c07875-8adc-4707-a189-2bc153bbfb2f.png)

![image](https://user-images.githubusercontent.com/10724598/142626944-1bc89868-17c9-4417-b55f-f20ae26f7f13.png)

Perhaps you should investigate your `wasm` binary - is the `malloc` symbol defined and exported there? Is it called something else? If so you should plug the right symbol name into `mallocName`. If nothing seems to make sense, perhaps the WASI ecosystem has changed since I last looked at this project.

**HOWEVER**, it seems like you want a way to use wasm2lua without `libc`. I can certainly add a flag to include a stub `malloc` in, but that'd mean that I have to dig my hands into a repository that I haven't touched in a while and do scary things to it.

Perhaps what you can try instead is to define your own stub `malloc` export in the code you're writing.
```c++
extern "C" void* malloc(int size) {
  return 0;
}
```
Something like that should be enough for your troubles.

I hope this.. helps? Unfortunately I'm held up with real life responsibilities and other projects, so I can't do very much here unless things are looking dire.

**Comment by SwadicalRag** [comment]
I lied, sorry I fixed it.

You can try the above fix, or by running wasm2lua with the `nolibc` flag

**Comment by Vurv78** [comment]
Awesome, tysm!
